spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_33_shop
    username: postgres
    password: h2s3VPJAMSIDE
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml